from ipp_toolkit.config import UNCERTAINTY_KEY


class BaseInterestingessComputer:
    def compute_interestingness(self, prediction_dict: dict):
        """
        prediction_dict:
            The predictions generated by a predictor. It should contain
            a predicted value and optionally an uncertainty
        """
        raise NotImplementedError()


class UncertaintyInterestingessComputer(BaseInterestingessComputer):
    def compute_interestingness(self, prediction_dict: dict):
        try:
            uncertainty = prediction_dict[UNCERTAINTY_KEY]
            return uncertainty

        except KeyError:
            raise ValueError(
                "UncertaintyInterestingessComputer must be used with an UncertainPredictor"
            )
